<?php
include_once "sites/all/library/dbmng/dbmng.php";
include_once "sites/all/library/dbmng/dbmng_sql_functions.php";

//******************************************************************************
// Drupal Module 
// ====================
// Query
//******************************************************************************

function dbmng_block_info() {
$blocks = array();
$blocks['lst_tables'] = array(
'info' => t('List tables'),
);

return $blocks;
}

function dbmng_block_view($delta='') {
$block = array();

switch($delta) {
	case 'lst_tables':
		$block['content'] = dbmng_list_table_view();
		break;
}

return $block;
}

function dbmng_menu() {
    $items = array();

    $items['dbmng/dbmng'] = array(
        'title' => 'Database Management',
        'page callback' => 'dbmng_manager',
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
     );

 		$items['dbmng/edit_tables'] = array(
        'title' => 'Edit Table',
        'page callback' => 'dbmng_edit_tables',
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
     );

    return $items;
}

function dbmng_list_table_view() {
$html='';
$result = dbmng_query('SELECT distinct id_table, table_label, table_name FROM dbmng_tables where id_table_type=:id_table_type order by table_label ',array(':id_table_type'=>2));
	$html.="<ul>";
		foreach ($result as $record) {

			$tn=t($record->table_label);
			if($tn==''){
				$tn=$record->table_name;
			}

			$html.="<li><a href='?tbl=" . $record->id_table . "'>" . $tn . "</li>";
		}
	$html.='</ul>';
return $html;
}

function dbmng_add_libraries()
	{
		drupal_add_css( "sites/all/modules/dbmng_module/dbmng_module.css" );
		drupal_add_css( "sites/all/library/dbmng/assets/dbmng.css" );
		drupal_add_js ( "sites/all/library/dbmng/assets/dbmng.js" );
		drupal_add_library('system','ui.datepicker');
	}


function dbmng_manager() 
{
	$id_table_table=8;
	$id_table_field=9;
	dbmng_add_libraries();

	$html = "";
	if( isset($_REQUEST['tbl']) )
	{
		//get the form!!!
		$id_table = $_REQUEST['tbl'];
		$aForm    = dbmng_get_form_array($id_table);

		//the param array stores some custom variable used by the renderer
		//hidden_vars are some hidden variables used by the form creation
		global $user;
		unset($aParam);
		$aParam                            = array();
		$aParam['filters']                 = array();
		$aParam['hidden_vars']             = array();
		$aParam['hidden_vars']['tbl']	     = $_REQUEST['tbl']; //save the table id
		$aParam['hidden_vars']['type_tbl'] = 2; //table type (1: content table; 2: system table)

		//test filter records with a specific uid
		//$aParam['filters']['id_user']	   = $user->uid;       // save the user id
		$aParam['tbl_footer']              = 1;                // allow to add filtering
		$aParam['user_function']['dup']	   = 0;	              // allow to enabled=1 or disabled=0 the duplication function
		$aParam['user_function']['ins']	   = 1;	              // allow to enabled=1 or disabled=0 the insert function
		$aParam['user_function']['upd']	   = 1;                // allow to enabled=1 or disabled=0 the update function
		$aParam['user_function']['del']	   = 0;	              // allow to enabled=1 or disabled=0 the delate function
		$aParam['file']                    = "sites/default/upload/";
		$aParam['tbl_order']               = 'nome';

		//print_r ($aParam['filters']);

		// update record
		dbmng_create_form_process($aForm, $aParam);

		$html .= dbmng_create_table($aForm, $aParam);

		$html .= dbmng_create_form($aForm, $aParam);
	}
	else{
		if( isset($_REQUEST['test']) )
			{


				$rs=dbmng_query("select * from test");
					foreach($rs as $r){
						//print_r($r);
						//echo('_'.$r->id_test.'_<br/>');
					}


				$aForm=array(  
					'table_name' => 'test' ,
					'primary_key'=> array('id_test'), 
					'fields'     => array(
						'nome' => array('label' => 'Name', 'type' => 'varchar') ,
						'eta'  => array('label'   => 'Et&agrave;' , 'type' => 'int'    )
					)
        );
				$aParam=array();
				$aParam['hidden_vars']['test']  = $_REQUEST['test'];
				$html .= dbmng_crud($aForm, $aParam);

			}
		elseif( isset($_REQUEST['show_fields']) )
			{

				//$aForm    = dbmng_get_form_array($id_table_field);
				$sql    = 'select COLUMN_NAME as colname FROM information_schema.columns c, dbmng_tables t WHERE t.table_name=c.table_name AND t.id_table =:id_table;';
				/*
				if( isset($_REQUEST['upd_dbmng_fields']) ) //$_REQUEST["upd_" . $aForm['table_name']]
					{
						$sql    = 'select COLUMN_NAME as colname ';
						$sql   .= 'FROM information_schema.columns c, ' . DBMNG_DB_NAME . '.dbmng_tables t ';
						$sql   .= 'WHERE COLUMN_NAME not in( select field_name from ' . DBMNG_DB_NAME . '.dbmng_fields where id_table = :id_table ) ';
						$sql   .= 'AND t.table_name=c.table_name AND t.id_table =:id_table;';
					}
				*/
				$fields = dbmng_query($sql, array(':id_table' => $_REQUEST['show_fields']));
				$varField= array();
				foreach($fields as $f)
					{				
						$cn=	 $f->colname;

						$varField[$cn] = $cn ;
					}		

				$aForm=array(  
						'table_name' => 'dbmng_fields' ,
							'primary_key'=> array('id_field'), 
							'fields'     => array(
									'field_name'  => 
										array('label'   => t('Name') , 
													'label_long' => t('Field Name'),
													'nullable' => false,
													'type' => 'varchar',
													'widget'=>'select' ,
											    'voc_val' => $varField
    
										), 
									'field_label'  => 
										array('label'   => t('Label') , 
													'label_long' => t('Field Label'),
													'nullable' => false,
													'type' => 'varchar'
										), 
									'id_field_type'     => 
										array('label'   => t('Type'), 
													'label_long' => t('Field Type'),
													'type' => 'varchar', 
													'widget'=>'select' ,
													'nullable' => false,
													'voc_val' => array(
														'int'=> t('Integer'),	
														'varchar'=> t('Short Text'),	
														'text'=> t('Long Text'),	
														'date'=> t('Date')	
													)
										) ,
									'field_widget'     => 
										array('label'   => t('Widget'), 
													'label_long' => t('Widget'),
													'type' => 'varchar', 
													'widget'=>'select' ,
													'nullable' => false,
													'voc_val' => array(
															'checkbox'=> t('CheckBox'),	
															'date'=> t('Date'),	
															'file'=> t('File'),
															'input'=> t('Input Box'),	
															'select'=> t('Select'),	
															'textarea'=> t('Text Area')	
													)
										),
									'nullable'     => 
										array('label'   => t('Null'), 
													'label_long' => t('Nullable'),
													'type' => 'int', 
													'widget'=>'checkbox',
													'skip_in_tbl' => '1'
										),
									'pk'     => 
										array('label'   => t('Pk'), 
													'label_long' => t('Primary Key'),
													'type' => 'int', 
													'widget'=>'checkbox'
										),
									'default_value' =>
										array( 'label' => t('Default'),
													 'label_long' => t('Default value'),
													 'type'  => 'varchar',
													 'skip_in_tbl' => '1'
										),
									'field_function' =>
										array( 'label' => t('Fnc'),
													 'label_long' => t('Field function'),
													 'type'  => 'varchar',
													 'skip_in_tbl' => '1'
										),
									'field_label_long' =>
										array( 'label' => t('Long'),
													 'label_long' => t('Long Label'),
													 'type'  => 'varchar',
													 'skip_in_tbl' => '1'
										),
									'field_order' =>
										array( 'label' => t('Order'),
													 'label_long' => t('Order'),
													 'type'  => 'int',
										),
									'skip_in_tbl'     => 
										array('label'   => t('Skip'), 
													'label_long' => t('Skip in table view'),
													'type' => 'int', 
													'widget'=>'checkbox',
													'skip_in_tbl' => '1'
										),
									'voc_sql' =>
										array( 'label' => t('SQL'),
													 'label_long' => t('Vocabulary SQL'),
													 'type'  => 'text',
													 'widget' => 'textarea',
													 'skip_in_tbl' => '1'
										),							
									'field_function'     => 
										array('label'   => t('Fnc'), 
													'label_long' => t('Field function'),
													'type' => 'varchar', 
													'skip_in_tbl' => '1'
										),
							)
					);

				unset($aParam);
				$aParam                            = array();
				$aParam['filters']['id_table']	   = $_REQUEST['show_fields']; 
				$aParam['hidden_vars']['show_fields']  = $_REQUEST['show_fields'];
				$aParam['user_function']['dup']	   = 0;	              // allow to enabled=1 or disabled=0 the duplication function
				$aParam['user_function']['del']	   = 0;	              // allow to enabled=1 or disabled=0 the delate function
				$aParam['tbl_order']               = 'field_order';
				$html .= dbmng_crud($aForm, $aParam);
			}
		else
			{
				// $aForm    = dbmng_get_form_array($id_table_table);
				$aForm=array(  
						'table_name' => 'dbmng_tables' ,
							'primary_key'=> array('id_table'), 
							'fields'     => array(
									'table_name'  => 
										array('label'   => t('Name') , 
													'label_long' => t('Table Name'),
													'type' => 'varchar'
										), 
									'id_table_type'     => 
										array('label'   => t('Type'), 
													'label_long' => t('Table Type'),
													'type' => 'varchar', 
													'widget'=>'select' ,
													'voc_val' => array(
														'1'=> t('Content Table'),	
														'2'=> t('System Table')
													)
										) ,
									'table_label'  => 
										array('label'   => t('Label') , 
													'label_long' => t('Table Label'),
													'type' => 'varchar',
													'skip_in_tbl' => '1'
										), 
									'table_desc'  => 
										array('label'   => t('Desc') , 
													'label_long' => t('Table Description'),
													'type' => 'varchar',
													'skip_in_tbl' => '1'
										)
							)
					);

				unset($aParam);
				$aParam                            = array();
				$aParam['user_function']['dup']	   = 0;	              // allow to enabled=1 or disabled=0 the duplication function
				$aParam['user_function']['del']	   = 0;	              // allow to enabled=1 or disabled=0 the delate function
				$aParam['custom_function'][0]['custom_variable']  = 'show_fields';
				$aParam['custom_function'][0]['custom_label']  = t('Show Fields');

				// update record
				$html .= dbmng_crud($aForm, $aParam);
		}
	}
  return ($html);
}

function dbmng_edit_tables() 
	{
	  dbmng_add_libraries();

		$table = 'test';
		
		$html  = t('Document page');
		if( isset($_REQUEST['tbl']) )
		{
			//get the form!!!
			$id_table = $_REQUEST['tbl'];
			$aForm    = dbmng_get_form_array($id_table);

			//the param array stores some custom variable used by the renderer
			//hidden_vars are some hidden variables used by the form creation
			global $user;
			unset($aParam);
			$aParam                          = array();
			$aParam['filters']               = array();
			$aParam['hidden_vars']           = array();
			$aParam['hidden_vars']['tbl']	   = $_REQUEST['tbl']; //save the table id
		  $aParam['hidden_vars']['type_tbl'] = 1; //table type (1: content table; 2: system table)

			//test filter records with a specific uid
			//$aParam['filters']['id_user']	   = $user->uid;       // save the user id
			$aParam['tbl_footer']            = 1;                // allow to add filtering
			$aParam['user_function']['dup']	 = 1;	              // allow to enabled=1 or disabled=0 the duplication function
			$aParam['user_function']['ins']	 = 1;	              // allow to enabled=1 or disabled=0 the insert function
			$aParam['user_function']['upd']	 = 1;                // allow to enabled=1 or disabled=0 the update function
			$aParam['user_function']['del']	 = 1;	              // allow to enabled=1 or disabled=0 the delate function
			$aParam['file']                  = "sites/default/upload/";
			// update record
			$html .= dbmng_crud($aForm, $aParam);
		}
	return ($html);
}

