<?php
include_once "sites/all/library/dbmng/dbmng.php";

//******************************************************************************
// Drupal Module 
// ====================
// Query
//******************************************************************************

function dbmng_block_info() {
$blocks = array();
$blocks['lst_tables'] = array(
'info' => t('List tables'),
);

return $blocks;
}

function dbmng_block_view($delta='') {
$block = array();

switch($delta) {
	case 'lst_tables':
		$block['content'] = dbmng_list_table_view();
		break;
}

return $block;
}

function dbmng_menu() {
    $items = array();

    $items['dbmng/dbmng'] = array(
        'title' => 'Database Management',
        'page callback' => 'dbmng_manager',
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
     );

 		$items['dbmng/edit_tables'] = array(
        'title' => 'Edit Table',
        'page callback' => 'dbmng_edit_tables',
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
     );

    return $items;
}

function dbmng_list_table_view() {
$html='';
$result = db_query('SELECT distinct id_table, table_label, table_name FROM dbmng_tables where id_table_type=2 order by table_label ');
	$html.="<ul>";
		foreach ($result as $record) {

			$tn=t($record->table_label);
			if($tn==''){
				$tn=$record->table_name;
			}

			$html.="<li><a href='?tbl=" . $record->id_table . "'>" . $tn . "</li>";
		}
	$html.='</ul>';
return $html;
}

function dbmng_add_libraries()
	{
		drupal_add_css( "sites/all/modules/dbmng_module/dbmng_module.css" );
		drupal_add_css( "sites/all/library/dbmng/assets/dbmng.css" );
		drupal_add_js ( "sites/all/library/dbmng/assets/dbmng.js" );
		drupal_add_library('system','ui.datepicker');
	}


function dbmng_manager() 
{
	$id_table_table=8;
	$id_table_field=9;
	dbmng_add_libraries();

	$html = "";
	if( isset($_REQUEST['tbl']) )
	{
		//get the form!!!
		$id_table = $_REQUEST['tbl'];
		$aForm    = dbmng_get_form_array($id_table);

		//the param array stores some custom variable used by the renderer
		//hidden_vars are some hidden variables used by the form creation
		global $user;
		unset($aParam);
		$aParam                            = array();
		$aParam['filters']                 = array();
		$aParam['hidden_vars']             = array();
		$aParam['hidden_vars']['tbl']	     = $_REQUEST['tbl']; //save the table id
		$aParam['hidden_vars']['type_tbl'] = 2; //table type (1: content table; 2: system table)

		//test filter records with a specific uid
		//$aParam['filters']['id_user']	   = $user->uid;       // save the user id
		$aParam['tbl_footer']              = 1;                // allow to add filtering
		$aParam['user_function']['dup']	   = 0;	              // allow to enabled=1 or disabled=0 the duplication function
		$aParam['user_function']['ins']	   = 1;	              // allow to enabled=1 or disabled=0 the insert function
		$aParam['user_function']['upd']	   = 1;                // allow to enabled=1 or disabled=0 the update function
		$aParam['user_function']['del']	   = 0;	              // allow to enabled=1 or disabled=0 the delate function

		//print_r ($aParam['filters']);

		// update record
		dbmng_create_form_process($aForm, $aParam);

		$html .= dbmng_create_table($aForm, $aParam);

		$html .= dbmng_create_form($aForm, $aParam);
	}
	else{


		if( isset($_REQUEST['test']) )
			{

				$aForm=array(  
					'table_name' => 'test' ,
					'primary_key'=> array('id_test'), 
					'fields'     => array(
						'nome' => array('label' => 'Name', 'type' => 'varchar') ,
						'eta'  => array('label'   => 'Et&agrave;' , 'type' => 'int'    )
					)
        );
				$aParam=array();
				$aParam['hidden_vars']['test']  = $_REQUEST['test'];
				$html .= dbmng_crud($aForm, $aParam);

			}
		elseif( isset($_REQUEST['show_fields']) )
			{

				$aForm    = dbmng_get_form_array($id_table_field);
				$aParam                            = array();
				$aParam['filters']['id_table']	   = $_REQUEST['show_fields']; 
				$aParam['hidden_vars']['show_fields']  = $_REQUEST['show_fields'];
				$aParam['user_function']['dup']	   = 0;	              // allow to enabled=1 or disabled=0 the duplication function
				$aParam['user_function']['del']	   = 0;	              // allow to enabled=1 or disabled=0 the delate function

				$html .= dbmng_crud($aForm, $aParam);

			}
		else
			{


				$aForm    = dbmng_get_form_array($id_table_table);
				$aParam                            = array();
				$aParam['user_function']['dup']	   = 0;	              // allow to enabled=1 or disabled=0 the duplication function
				$aParam['user_function']['del']	   = 0;	              // allow to enabled=1 or disabled=0 the delate function
				$aParam['custom_function'][0]['custom_variable']  = 'show_fields';
				$aParam['custom_function'][0]['custom_label']  = t('Show Fields');


				// update record
				$html .= dbmng_crud($aForm, $aParam);
		}
			
	}
  return ($html);
}




function dbmng_edit_tables() 
	{
	  dbmng_add_libraries();

		$table = 'test';
		
		$html  = t('Document page');
		if( isset($_REQUEST['tbl']) )
		{
			//get the form!!!
			$id_table = $_REQUEST['tbl'];
			$aForm    = dbmng_get_form_array($id_table);

			//the param array stores some custom variable used by the renderer
			//hidden_vars are some hidden variables used by the form creation
			global $user;
			unset($aParam);
			$aParam                          = array();
			$aParam['filters']               = array();
			$aParam['hidden_vars']           = array();
			$aParam['hidden_vars']['tbl']	   = $_REQUEST['tbl']; //save the table id
		$aParam['hidden_vars']['type_tbl'] = 1; //table type (1: content table; 2: system table)

			//test filter records with a specific uid
			$aParam['filters']['id_user']	   = $user->uid;       // save the user id
			$aParam['tbl_footer']            = 1;                // allow to add filtering
			$aParam['user_function']['dup']	 = 1;	              // allow to enabled=1 or disabled=0 the duplication function
			$aParam['user_function']['ins']	 = 1;	              // allow to enabled=1 or disabled=0 the insert function
			$aParam['user_function']['upd']	 = 1;                // allow to enabled=1 or disabled=0 the update function
			$aParam['user_function']['del']	 = 1;	              // allow to enabled=1 or disabled=0 the delate function

			// update record
			$html .= dbmng_crud($aForm, $aParam);
		}
	return ($html);
}

