<?php

include_once "sites/all/libraries/dbmng/dbmng.php";
include_once "sites/all/libraries/jpgraph/src/jpgraph.php";
include_once "sites/all/libraries/jpgraph/src/jpgraph_radar.php";
 

//******************************************************************************
// Drupal Module 
// ====================
// Query
//******************************************************************************
function climasouth_block_info() 
{
	$blocks = array();
	$blocks['climasud_test'] = array(
		'info' => t('Climasouth test block'),
		);
	$blocks['climasouth_login'] = array(
		'info' => t('Climasouth Login block'),
		);
	$blocks['climasouth_map'] = array(
		'info' => t('Climasouth Map block'),
		);
	$blocks['climasouth_toolbar'] = array(
		'info' => t('Climasouth Toolbar'),
		);
	$blocks['climasouth_news'] = array(
		'info' => t('Climasouth news'),
		);
	$blocks['climasouth_menu_country'] = array(
		'info' => t('Climasouth menu country'),
		);
	$blocks['climasouth_menu_contacts'] = array(
		'info' => t('Climasouth menu contacts'),
		);
	$blocks['climasouth_contribute_view'] = array(
		'info' => t('Climasouth contribute view'),
		);
	$blocks['climasouth_contribute_edit'] = array(
		'info' => t('Climasouth contribute edit'),
		);
	
	return $blocks;
}

function climasouth_block_view($delta='') 
{
	$block = array();
	
	switch($delta) 
		{
			case 'climasud_test' :
				$block['content'] = _climasouth_block();
				break;
			case 'climasouth_map' :
				$block['content'] = _climasouth_map_block();
				break;
			case 'climasouth_login' :
				$block['content'] = _climasouth_login();
				break;
			case 'climasouth_toolbar' :
				$block['content'] = _climasouth_toolbar();
				break;
			case 'climasouth_news' :
				$block['content'] = _climasouth_news();
				break;
			case 'climasouth_menu_country' :
				$block['content'] = _climasouth_menu_country();
				break;
			case 'climasouth_menu_contacts' :
				$block['content'] = _climasouth_menu_contacts();
				break;
			case 'climasouth_contribute_view' :
				$block['content'] = _climasouth_contribute_view();
				break;
			case 'climasouth_contribute_edit' :
				$block['content'] = _climasouth_contribute_edit();
				break;
		}
	
	return $block;
}

function _climasouth_map_block() 
{
	dbmng_add_drupal_libraries();

	$html =  _climasouth_maps(true);

	return $html;
}


/* NOT Workig
function climasouth_init() 
{
	echo $_GET['q'];
	if(isset($_GET['q']) ) {
		if( $_GET['q'] == 'climasouth/workspace/resource/view') {
		  drupal_goto('climasouth/workspace?act=ins&tbl=c_resource');
       
    }
	}
}
*/

function climasouth_url_inbound_alter(&$path, $original_path, $path_language) {
	
		if( $path == 'climasouth/resource/view') {
       $path = 'climasouth/workspace';
			 $_REQUEST['act'] = 'search';
			 $_REQUEST['tbl'] = 'c_resource';
    }  
		else if ( $path == 'climasouth/resource/edit') {
       $path = 'climasouth/workspace';
			 $_REQUEST['act'] = 'ins';
			 $_REQUEST['tbl'] = 'c_resource';
    }  
}

function _climasouth_block() 
{
	$html = "";

	return $html;
}

function _climasouth_login() 
{
	$html = '<div id="climasouth_login">';	
	global $user;

	if ($user->uid) 
		{
		 $html .= '<span class="climasouth_username">'.l($user->name, 'user').'</span> - ';
		 $html .= l(t('log out'), 'user/logout');
		}
	else
		{
			$html .=  l(t('log in'), 'user');
		}

	$html.='</div>';
	return $html;
}


function _climasouth_toolbar() 
{
	global $base_path;
	
	$aClass = array('attributes' => array('class' => array('toolbar_link')));
	$html = '<div id="climasouth_toolbar">';	
	$html .= "<ul id='climasouth_toolbar_ul'>";
	$html .= "<li class='climasouth_toolbar'>".t('Multimedia')."</li>";
	$html .= "<li class='climasouth_toolbar'>".t('Press Packs')."</li>";
	$html .= "<li class='climasouth_toolbar'>".t('CC Knowledge Navigator')."</li>";
	$html .= "<li class='climasouth_toolbar'>".l(t('Contacts'), 'contacts', $aClass)."</li>";
	//l(t('log out'), 'user/logout')
	$html .= "</ul>";

	$html.='</div>';
	return $html;
}

function _climasouth_news() 
{
	$html = '<div id="climasouth_news">';
	$html .= '<h2 id="climasouth_news_h2">'.l(t('News & Events'),'news_events').'</h2>';	
	
	/** load dinamically from database*/
	$html .= "<ul>";
	
	$res = dbmng_query("select * from c_news order by date_from", array());
	foreach ($res as $rec) {
		$place = $rec->place;
		$title = $rec->title;
		$date_from = new DateTime($rec->date_from);
		$date_to = $rec->date_to;
		$node = $rec->linked_page;
		if(isset($date_to))
			$date_to = new DateTime($rec->date_to);

		$days = $date_from->format("d");
		$months = $date_from->format("F");
		$year = $date_from->format("Y");
		
		if( isset($date_to) )
			{
				$date_to = new DateTime($rec->date_to);
				$days .= "-".$date_to->format("d");
				
				if( $months != $date_to->format("F") )
					$months .= " ".$date_to->format("F");

				if( $year != $date_to->format("Y") )
					$months .= " ".$date_to->format("Y");
			}
		$date = $days." ".$months." ".$year;
		
		$html.="<li class='climasouth_news'>".$place . " " . $date . "<br/>" . l($title,$node)."</li>";
	}
	
	$html .= "</ul>";
	
	$html.='</div>';
	return $html;
}

function _climasouth_menu_country()
{
	$html = "";
	if( isset($_REQUEST['id_c_country']) )
		{
			$html = '<div id="climasouth_menu_country">';
			$html .= "<ul>";
			$html .= "<li class='climasouth_menu_country_li'>".t('Overview & key data')."</li>";
			$html .= "<li class='climasouth_menu_country_li'>".t('National climate policy')."</li>";
			$html .= "<li class='climasouth_menu_country_li'>".t('National reports')."</li>";
			$html .= "<li class='climasouth_menu_country_li'>".t('Climate Change projects')."</li>";
			$html .= "<li class='climasouth_menu_country_li'>".t('Focal Point')."</li>";
			$html .= "<li class='climasouth_menu_country_li'>".t('EU Delegation')."</li>";
			$html .= "</ul>";
		
			$html.='</div>';
		}
	return $html;
}

function _climasouth_menu_contacts()
{
	$html = "";
	$html = '<div id="climasouth_menu_contacts">';
	$html .= "<ul>";
	$html .= "<li class='climasouth_menu_contacts_li'>".t('EC/ DEVCO')."</li>";
	$html .= "<li class='climasouth_menu_contacts_li'>".t('EC/ DGCLIMA')."</li>";
	$html .= "<li class='climasouth_menu_contacts_li'>".t('National Focal Points')."</li>";
	$html .= "<li class='climasouth_menu_contacts_li'>".t('EU Delegations')."</li>";
	$html .= "<li class='climasouth_menu_contacts_li'>".t('Agriconsulting Consortium')."</li>";
	$html .= "</ul>";

	$html.='</div>';
	return $html;
}

function _climasouth_contribute_view()
{
	$html = "";

	

	$_REQUEST['tbl'] = 'c_resource';
	$html = _climasouth_workspace();

	return $html;
}

function _climasouth_contribute_edit()
{
	$html = "";

	$_REQUEST['tbl'] = 'c_resource';
	$_REQUEST['act'] = 'ins';
	$html = _climasouth_workspace();

	return $html;
}

function climasouth_menu() 
{
  $items = array();

  $items['climasouth/country'] = array(
      'title' => 'List of Countries',
      'page callback' => 'lst_country',
      'access arguments' => array('access content'),
      'type' => MENU_CALLBACK,
   );

  $items['climasouth/workspace'] = array(
      'title' => 'Collaborative Workspaces',
      'page callback' => '_climasouth_workspace',
      'access arguments' => array('view workspace'),
      'type' => MENU_CALLBACK,
   );

  $items['climasouth/assistance'] = array(
      'title' => 'Request Assistance',
      'page callback' => '_climasouth_assistance',
      'access arguments' => array('view workspace'),
      'type' => MENU_CALLBACK,
   );

  return $items;
}

function lst_country() 
{
	//important add dbmng js & css
	dbmng_add_drupal_libraries();

	$html = "";

	if(isset($_REQUEST['id_c_country']))
		{
			$id_c_country=$_REQUEST['id_c_country'];
			
			$res = dbmng_query('select * from c_country WHERE id_c_country=:id_c_country', array('id_c_country' => intval($id_c_country) ));
			
			$cnt = dbmng_fetch_object($res);

			//$html.='<h3>'.$cnt->country_name.'</h3>';

			drupal_set_title(t($cnt->country_name));
			
						
			$html.= '<div id="climasouth_country">';

			if(	$cnt->flag !=null)
				{				
					$html.='<img id="climasouth_flag" src="'.base_path().$cnt->flag.'" />';
				}			 

			if(	$cnt->html_content !=null)
				{				
					$html.='<div id="climasouth_country_content">'.$cnt->html_content.'</div>';
				}			 
			
			$aCountry = array();
			$aCountry['id_c_country'] = $id_c_country;
			$aCountry['country_name'] = $cnt->country_name;

			//$file = _climasouth_graph( $aCountry );
			//if(strlen($file)>0)
			//	{
			//		$html .= '<img class="climasouth_radar_chart"  id="climasouth_graph" src="'.base_path().$file.'" />';
			//	}			
			$html.= '</div>';
		}
	else 
		{
			 $html.=  _climasouth_maps(false);
		}
	
	$html .= implode(' ', service_links_render(null, FALSE));  
return ($html);
}

function _climasouth_assistance()
{
	dbmng_add_drupal_libraries();
	$aForm=array(  
			'table_name' => 'c_requeste_assistance' ,
				'primary_key'=> array('id_c_requeste_assistance'), 
				'fields'     => array(
						'id_c_requeste_assistance'  => 
							array('label'   => t('ID') , 
										'label_long' => t('ID Table'),
										'type' => 'bigint',
										'skip_in_tbl' => '1',
										'key' => 1
							), 
						'req_name'  => 
							array('label'   => t('Your name (required)') , 
										'type' => 'varchar',
										'widget' => 'input',
										'nullable' => false,
										'key' => 0
							), 
						'req_email'     => 
							array('label'   => t('Your email (required)'), 
										'type' => 'varchar', 
										'widget'=>'input' ,
										'nullable' => false,
										'key' => 0
							) ,
						'req_organisation'  => 
							array('label'   => t('Your organisation') , 
										'type' => 'varchar',
										'key' => 0,
										'skip_in_tbl' => '1'
							), 
						'req_message'  => 
							array('label'   => t('Your message') , 
										'type' => 'varchar',
										'widget'=>'html' ,
										'key' => 0,
										'skip_in_tbl' => '1'
							),
						'req_file'  => 
							array('label'   => t('Attach File') , 
										'type' => 'varchar',
										'widget'=>'file' ,
										'key' => 0,
										'skip_in_tbl' => '1'
							)
				)
		);
	
	$aParam = array();
	$aParam['ui']['btn_name'] = "Send";
	$aParam['captcha'] = 1;
	
	$html = "";
	if( !isset($_POST['req_name']) )
		{
			$html .= dbmng_create_form($aForm, $aParam, 0);
		}
	else
		{	
			if( isset($_POST['captcha']) )
				{
					if( intval($_POST['captcha']) == intval($_POST['dbmng_x'])+intval($_POST['dbmng_y']) )
						{
							$to      = 'info@climasouth.eu';
							$subject = '[climasouth] Request assistance';
							$message = $_POST['req_message'];

							// To send HTML mail, the Content-type header must be set
							$headers  = 'MIME-Version: 1.0' . "\r\n";
							$headers .= 'Content-type: text/html; charset=iso-8859-1' . "\r\n";
							$headers .= 'From: '.$_POST['req_email'].'' . "\r\n" .
							    'Reply-To: '.$_POST['req_email']."\r\n" .
							    'X-Mailer: PHP/' . phpversion();
							$attachfile = $_FILES['req_file'];
							
							mail($to, $subject, $message , $headers);
							climasouth_mailto($attachfile);
							
							$html .= "To: ".$to."<br/>Subject: ".$subject;
							$html .= "Message: ".$message."<br/>headers: ".$headers."<br/>";
							$html .= "Attach file: ".$attachfile."<br/>";
							$html .= "Your request has been sent ...";
						}
					else
						{
							$html .= t("wrong captcha!");
							$html .= dbmng_create_form($aForm, $aParam, 3);
						}
				}
			else
				{
					$html .= t("insert captcha!");
					$html .= dbmng_create_form($aForm, $aParam, 3);
				}
		}
	
	return $html;
}

function climasouth_mailto($attfile)
{
	$htmlbody = " Your Mail Contant Here.... You can use html tags here...";
	$to = "info@climasouth.eu"; //Recipient Email Address
	$subject = "Test email with attachment"; //Email Subject
	$headers = "From: name@domain.com\r\nReply-To: name@domain.com";
	$random_hash = md5(date('r', time()));
	$headers .= "\r\nContent-Type: multipart/mixed; 
	boundary=\"PHP-mixed-".$random_hash."\"";
	// Set your file path here
	$attachment = chunk_split(base64_encode(file_get_contents($attfile['tmp_name']))); 
	
	
	//define the body of the message.
	$message = "--PHP-mixed-$random_hash\r\n"."Content-Type: multipart/alternative; 
	boundary=\"PHP-alt-$random_hash\"\r\n\r\n";
	$message .= "--PHP-alt-$random_hash\r\n"."Content-Type: text/plain; 
	charset=\"iso-8859-1\"\r\n"."Content-Transfer-Encoding: 7bit\r\n\r\n";
	
	
	//Insert the html message.
	$message .= $htmlbody;
	$message .="\r\n\r\n--PHP-alt-$random_hash--\r\n\r\n";
	
	
	//include attachment
	$message .= "--PHP-mixed-$random_hash\r\n"."Content-Type: application/zip; 
	name=".$attfile['name']."\r\n"."Content-Transfer-Encoding: 
	base64\r\n"."Content-Disposition: attachment\r\n\r\n";
	
	$message .= $attachment;
	$message .= "/r/n--PHP-mixed-$random_hash--";
	
	
	//send the email
	$mail = mail( $to, $subject , $message, $headers );
	
	echo $mail ? "Mail sent" : "Mail failed";
}

function _climasouth_graph( $aCountry )
{
	$id_c_country = $aCountry['id_c_country'];
	$country_name = $aCountry['country_name'];
	
	$aPlot   = array();
	$aRadar0 = array();
	$aRadar1 = array();
	$aRadar2 = array();
	
	//Query to get the titles of the radar plot
	$sql = "select ass_type from c_assessment where id_c_voc_ass_group = 1 order by id_c_assessment";
	$res = dbmng_query( $sql, array() );
	$aTitles = array();
	foreach($res as $r)
		{
			$aTitles[] = $r->ass_type;
		}
	
	//Query to get the reference target value
	$sql = "select 5 as reference from c_ghg_assessment where id_c_country = :id_c_country order by id_c_assessment";
	$res = dbmng_query($sql, array('id_c_country' => intval($id_c_country) ));
	$aVal0 = array();
	foreach($res as $r)
		{
			$aVal0[] = $r->reference;
		}
	
	//Query to get the proposed target value
	$sql = "select proposed_target from c_ghg_assessment where id_c_country = :id_c_country order by id_c_assessment";
	$res = dbmng_query($sql, array('id_c_country' => intval($id_c_country) ));
	$aVal1 = array();
	foreach($res as $r)
		{
			$aVal1[] = $r->proposed_target;
		}
	
	//Query to get the current rating value
	$sql = "select current_rating from c_ghg_assessment where id_c_country = :id_c_country order by id_c_assessment";
	$res = dbmng_query($sql, array('id_c_country' => intval($id_c_country) ));
	
	$aVal2 = array();
	foreach($res as $r)
		{
			$aVal2[] = $r->current_rating;
		}
	
	//reference
	$aRadar0['value']  = $aVal0;
	$aRadar0['legend'] = t("Reference"); 
	$aRadar0['color1'] = "black";
	$aRadar0['color2'] = "white";
	$aRadar0['mark']   = MARK_CROSS;
	
	//target
	$aRadar1['value'] = $aVal1;
	$aRadar1['legend']= t("Target");
	$aRadar1['color1'] = "blue";
	$aRadar1['color2'] = "white";
	$aRadar1['fill']   = "false";
	$aRadar1['line_weight'] = 2;
	$aRadar1['mark'] = MARK_IMG_STAR;
	
	//Current
	$aRadar2['value'] = $aVal2; 
	$aRadar2['legend']= t("Current rating");
	$aRadar2['color1'] = "red";
	$aRadar2['color2'] = "lightred";
	$aRadar2['line_weight'] = 10;
	$aRadar2['mark'] = MARK_IMG_SBALL;
	
	$aPlot['Title']      = t("Assessment of current GHG inventory preparation process versus needs in") . " " . $country_name;
	$aPlot['Titles']     = $aTitles;
	$aPlot['Filename']   = "GHG";
	$aPlot['width']      = 750;
	$aPlot['height']     = 400;
	$aPlot['background'] = "white";
	$aPlot['shadow']     = false;
	$aPlot['plot'][0]    = $aRadar0;
	$aPlot['plot'][1]    = $aRadar1;
	$aPlot['plot'][2]    = $aRadar2;
	
	if(count($aVal0)>0 && count($aVal1)>0 && count($aVal2)>0 )
		{
			$file = draw_radar_graph( $aPlot );
		}
	else
		{
			$file = '' ;
		}
	
	return $file;
}

function _climasouth_maps($block) 
{
	$html='';

	drupal_add_css( "sites/all/modules/climasouth/climasouth.css" );
	drupal_add_css('http://cdn.leafletjs.com/leaflet-0.6.4/leaflet.css',array('type' => 'external'));
	drupal_add_js('http://cdn.leafletjs.com/leaflet-0.6.4/leaflet.js',array('type' => 'external'));


	$aForm    = dbmng_get_form_array("c_country"); 	
	//TODO: do not change title if called in a block

	$height="350";
	if(!$block)
		{
			drupal_set_title(t("Countries"));
			$height="400";
		}

	$html .= '<div id="map_container" style="width:690px; height:'.$height.'px;"  ></div>';

	$html .= "\n<script type='text/javascript'>\n";
	$html .= "var data=".dbmng_get_js_array($aForm, null).";\n";
	$html .= "var aForm=".json_encode($aForm).";\n";
	$html .= "var aParam={ 'div_element':'map_container', 'zoom': 4, 'base_path':'".base_path()."', 'coord': [30, 13] };\n";
	$html .= "dbmng_leaflet(data,aForm, aParam);\n";
	$html .= "</script>\n";

	return $html;
}


function _climasouth_workspace() 
{

	

	dbmng_add_drupal_libraries();

	$html='';

	global $user;

	if ($user->uid) 
		{
			if( !isset($_REQUEST['tbl']) )
				{
					$html .= "Edit my data\n";
					$html .= "<ul>\n";
					$html .= "<li>add a  <a href='?act=ins&tbl=c_resource'>resources</a></li>\n";
					$html .= "<li>add an <a href='?act=ins&tbl=c_expert'>expert</a></li>\n"; 
					$html .= "<li>add an <a href='?act=ins&tbl=c_institution'>institution</a></li>\n";
					$html .= "<li>add an <a href='?act=ins&tbl=c_activity'>Monitoring and evaluation indicators</a></li>\n";
					$html .= "<li>add a link</li>\n";
					$html .= "<li>add a <a href='?act=ins&tbl=c_project'>project</a></li>\n";
					$html .= "</ul>\n";
					$html .= "Search my data\n";
					$html .= "<ul>\n";
					$html .= "<li><a href='?act=search&tbl=c_country'>Countries</a></li>\n";
					$html .= "<li><a href='?act=search&tbl=c_resource'>Search for resources</a></li>\n";
					$html .= "<li><a href='?act=search&tbl=c_expert'>Search for expert or organisation</a></li>\n";
					$html .= "<li><a href='?act=search&tbl=c_activity'>Search for M&E indicators</a></li>\n";
					$html .= "<li>Search for related project</li>\n";
					$html .= "</ul>\n";
				}

			if( isset($_REQUEST['tbl']) )
				{
					//get the form!!!
					$id_table = $_REQUEST['tbl'];
					$aForm    = dbmng_get_form_array(($id_table));
		
					//the param array stores some custom variable used by the renderer
					//hidden_vars are some hidden variables used by the form creation
					global $user;
					unset($aParam);
					$aParam                          = array();
					$aParam['filters']               = array();
					$aParam['hidden_vars']           = array();
					$aParam['hidden_vars']['tbl']	   = $_REQUEST['tbl']; //save the table id
					$aParam['user_function']['dup']	 = 0;	              // allow to enabled=1 or disabled=0 the duplication function
					$aParam['user_function']['prt_rec'] = 0;
					$aParam['user_function']['prt_tbl'] = 0;
					$aParam['tbl_sorter']              = '1';
					// update record
					$html .= dbmng_crud($aForm, $aParam);
				}
		}
	else 
		{
			$html.=t('Only for registered users');
		}

	return $html;
}

function climasouth_permission() {
	return array('view workspace' => array('title'=>t('Access to the collarative workspace')));
}

// this function must be moved outside this module
// Reference:
// Manual: http://jpgraph.net/download/manuals/chunkhtml/index.html
// Radar: http://jpgraph.net/download/manuals/chunkhtml/ch16s02.html
function draw_radar_graph( $aPlot )
{
	// Create the basic rtadar graph
	$graph = new RadarGraph($aPlot['width'], $aPlot['height']);
	 
	// Set background color and shadow
	$graph->SetColor($aPlot['background']);
	if( isset($aPlot['shadow']) )
		if( $aPlot['shadow'] )
			$graph->SetShadow();
	 
	// Position the graph
	$graph->SetCenter(0.5,0.55);
	 
	// Setup the axis formatting     
	//$graph->axis->SetFont(FF_ARIAL,FS_BOLD);
	$graph->axis->SetWeight(2);
	 
	// Setup the grid lines
	$graph->grid->SetLineStyle("longdashed");
	$graph->grid->SetColor("navy");
	$graph->grid->Show();
	$graph->HideTickMarks();
	        
	// Setup graph titles
	$graph->title->Set($aPlot["Title"]);
	//$graph->title->SetFont(FF_VERDANA,FS_BOLD);
	$graph->SetTitles($aPlot["Titles"]);
	
	foreach ($aPlot['plot'] as $p) 
		{
			$plot = new RadarPlot($p['value']);
			$plot->SetLegend($p['legend']);
			$plot->SetColor($p['color1'],$p['color2']);
			if( isset( $p['fill'] ) )
				$plot->SetFill($p['fill']);
			
			if( isset($p['line_weight']) )
				$plot->SetLineWeight(2);
			
			if( isset($p['mark']) )
				$plot->mark->SetType($p['mark'],$p['color1']);
			
			$graph->Add($plot);
		} 

	// And output the graph
	$dir = "sites/all/tmp/";
	$sFile = $aPlot['Filename'] . "_" . time() . ".png";
	$graph->Stroke($dir.$sFile);
	
	return $dir.$sFile;
} 
