<?php

include_once "sites/all/library/dbmng/dbmng.php";

//******************************************************************************
// Drupal Module 
// ====================
// Query
//******************************************************************************
function climasouth_block_info() 
{
	$blocks = array();
	$blocks['last_item'] = array(
		'info' => t('Last item'),
		);
	
	return $blocks;
}

function climasouth_block_view($delta='') 
{
	$block = array();
	
	switch($delta) 
		{
			case 'last_item' :
				$block['content'] = last_item_view();
				break;
		}
	
	return $block;
}

function last_item_view() {
$html='';
$result = db_query('SELECT distinct id_table, table_label, table_name FROM dbmng_tables where id_table_type=1 order by table_label ');
	$html.="<ul>";
		foreach ($result as $record) {

			$tn=t($record->table_label);
			if($tn==''){
				$tn=$record->table_name;
			}

			$html.="<li><a href='?tbl=" . $record->id_table . "'>" . $tn . "</li>";
		}
	$html.='</ul>';
return $html;
}

function climasouth_menu() 
{
  $items = array();

  $items['climasouth/country'] = array(
      'title' => 'List of Countries',
      'page callback' => 'lst_country',
      'access arguments' => array('access content'),
      'type' => MENU_CALLBACK,
   );

  return $items;
}

function lst_country() 
{
	drupal_add_css( "sites/all/modules/climasouth/climasouth.css" );
	$html = "lst_country";
	
  return ($html);

}