insert into c_assessment (strategy, ass_group, ass_type) values('Mitigation', 'Mitigation assessment', 'Mitigation scenario & policies');
insert into c_assessment (strategy, ass_group, ass_type) values('Mitigation', 'Mitigation assessment', 'Mitigation options');
insert into c_assessment (strategy, ass_group, ass_type) values('Mitigation', 'Mitigation assessment', 'Mitigation options by sector');
insert into c_assessment (strategy, ass_group, ass_type) values('Mitigation', 'Mitigation assessment', 'Technical needs assessment');
insert into c_assessment (strategy, ass_group, ass_type) values('Mitigation', 'Mitigation assessment', 'National expertise in mitigation');
insert into c_assessment (strategy, ass_group, ass_type) values('Mitigation', 'Mitigation assessment', 'National perception on mitigation options');
insert into c_assessment (strategy, ass_group, ass_type) values('Mitigation', 'Climate finance', 'Estimation of CO2 Ers');
insert into c_assessment (strategy, ass_group, ass_type) values('Mitigation', 'Climate finance', 'Costing of C02 Ers');
insert into c_assessment (strategy, ass_group, ass_type) values('Mitigation', 'Climate finance', 'Perception PS, FI & INS');
insert into c_assessment (strategy, ass_group, ass_type) values('Mitigation', 'Climate finance', 'CDM & P-CDM');
insert into c_assessment (strategy, ass_group, ass_type) values('Mitigation', 'Climate finance', 'NAMAs');
insert into c_assessment (strategy, ass_group, ass_type) values('Mitigation', 'Climate finance', 'LEDS formulation');
insert into c_assessment (strategy, ass_group, ass_type) values('Mitigation', 'Climate finance', 'NMMs');
insert into c_assessment (strategy, ass_group, ass_type) values('Mitigation', 'Climate finance', 'MRV');
insert into c_assessment (strategy, ass_group, ass_type) values('Mitigation', 'Assessment versus needs', 'Data Collection');
insert into c_assessment (strategy, ass_group, ass_type) values('Mitigation', 'Assessment versus needs', 'Data analysis');
insert into c_assessment (strategy, ass_group, ass_type) values('Mitigation', 'Assessment versus needs', 'Mitigation modeling');
insert into c_assessment (strategy, ass_group, ass_type) values('Mitigation', 'Assessment versus needs', 'Mitigation options identification');
insert into c_assessment (strategy, ass_group, ass_type) values('Mitigation', 'Assessment versus needs', 'Mitigation option costing');
insert into c_assessment (strategy, ass_group, ass_type) values('Mitigation', 'Assessment versus needs', 'MRV');
insert into c_assessment (strategy, ass_group, ass_type) values('Mitigation', 'Assessment versus needs', 'LEDS formulation');
insert into c_assessment (strategy, ass_group, ass_type) values('Mitigation', 'Assessment versus needs', 'Climate finance');

insert into c_assessment (strategy, ass_group, ass_type) values('Adaptation', 'Climate data & Modelling', 'Climate Observation network');
insert into c_assessment (strategy, ass_group, ass_type) values('Adaptation', 'Climate data & Modelling', 'Data Management');
insert into c_assessment (strategy, ass_group, ass_type) values('Adaptation', 'Climate data & Modelling', 'CC projection and modeling data');
insert into c_assessment (strategy, ass_group, ass_type) values('Adaptation', 'Climate data & Modelling', 'Sharing and data use to identify the vulnerability');
insert into c_assessment (strategy, ass_group, ass_type) values('Adaptation', 'Climate data & Modelling', 'Sharing data / use for adaptation analysis');
insert into c_assessment (strategy, ass_group, ass_type) values('Adaptation', 'Socio¬economic data ', 'Data availability for assessment');
insert into c_assessment (strategy, ass_group, ass_type) values('Adaptation', 'Socio¬economic data ', 'Data use for vulnerability identification');
insert into c_assessment (strategy, ass_group, ass_type) values('Adaptation', 'Socio¬economic data ', 'Data use for vulnerability assessment');
insert into c_assessment (strategy, ass_group, ass_type) values('Adaptation', 'Socio¬economic data ', 'Data use for the implementation of adaptation measures');
insert into c_assessment (strategy, ass_group, ass_type) values('Adaptation', 'Vulnerability assessment', 'A brief identification of vulnerability exist at the national level');
insert into c_assessment (strategy, ass_group, ass_type) values('Adaptation', 'Vulnerability assessment', 'Brief assessments of the vulnerability exist at the sectorial level?');
insert into c_assessment (strategy, ass_group, ass_type) values('Adaptation', 'Vulnerability assessment', 'Comprehensive assessments of vulnerability exist at the sectoral level?');
insert into c_assessment (strategy, ass_group, ass_type) values('Adaptation', 'Assessment of Adaptation to climate change', 'National vision for adaptation to CC');
insert into c_assessment (strategy, ass_group, ass_type) values('Adaptation', 'Assessment of Adaptation to climate change', 'National strategy/program /plan for adaptation to CC through addressing adverse effects and increasing climate resilience');
insert into c_assessment (strategy, ass_group, ass_type) values('Adaptation', 'Assessment of Adaptation to climate change', 'Sectoral strategies for adaptation to CC or to increase resilience');
insert into c_assessment (strategy, ass_group, ass_type) values('Adaptation', 'Assessment of Adaptation to climate change', 'Mainstreaming of CC/adaptation to CC in the strategic development planning process');
insert into c_assessment (strategy, ass_group, ass_type) values('Adaptation', 'Assessment of Adaptation to climate change', 'Costing of adaptation to climate change');
insert into c_assessment (strategy, ass_group, ass_type) values('Adaptation', 'Access to finance for adaptation', 'Are stakeholders informed about funding for adaptation to CC?');
insert into c_assessment (strategy, ass_group, ass_type) values('Adaptation', 'Access to finance for adaptation', 'Is there any CC adaptation projects clearly identified?');
insert into c_assessment (strategy, ass_group, ass_type) values('Adaptation', 'Access to finance for adaptation', 'Are these CC adaptation projects defined according to required formats?');
insert into c_assessment (strategy, ass_group, ass_type) values('Adaptation', 'Access to finance for adaptation', 'Do national capacities allow formulation of a project document, according to the formats required by donors?');
insert into c_assessment (strategy, ass_group, ass_type) values('Adaptation', 'Stakeholders awareness to adaptation to climate change', 'Level of stakeholders awareness to environmental challenges as well as CC/adaptation to CC');
insert into c_assessment (strategy, ass_group, ass_type) values('Adaptation', 'Stakeholders awareness to adaptation to climate change', 'Level of awareness of civil society/NGO to environmental challenges as well as CC/adaptation to CC');
insert into c_assessment (strategy, ass_group, ass_type) values('Adaptation', 'Stakeholders awareness to adaptation to climate change', 'Stakeholder’s understanding of adaptation to CC');
insert into c_assessment (strategy, ass_group, ass_type) values('Adaptation', 'Stakeholders awareness to adaptation to climate change', 'Civil society’s  understanding of adaptation to CC');
insert into c_assessment (strategy, ass_group, ass_type) values('Adaptation', 'Assessment versus needs', 'Climate data & modeling');
insert into c_assessment (strategy, ass_group, ass_type) values('Adaptation', 'Assessment versus needs', 'Socio-economic data availability');
insert into c_assessment (strategy, ass_group, ass_type) values('Adaptation', 'Assessment versus needs', 'Vulnerability Assessment');
insert into c_assessment (strategy, ass_group, ass_type) values('Adaptation', 'Assessment versus needs', 'Adaptation to CC');
insert into c_assessment (strategy, ass_group, ass_type) values('Adaptation', 'Assessment versus needs', 'Access to finance');
insert into c_assessment (strategy, ass_group, ass_type) values('Adaptation', 'Assessment versus needs', 'Level of Awareness');
