<?php

include_once "sites/all/library/dbmng/dbmng.php";

//******************************************************************************
// Drupal Module 
// ====================
// Query
//******************************************************************************
function enpimodule_block_info() {
$blocks = array();
$blocks['last_item'] = array(
'info' => t('Last item'),
);

return $blocks;
}

function enpimodule_block_view($delta='') {
$block = array();

switch($delta) {
case 'last_item' :
$block['content'] = last_item_view();
break;
}

return $block;
}

function last_item_view() {
$html='';
$result = db_query('SELECT distinct id_table, table_label, table_name FROM dbmng_tables order by table_label ');
	$html.="<ul>";
		foreach ($result as $record) {

			$tn=t($record->table_label);
			if($tn==''){
				$tn=$record->table_name;
			}

			$html.="<li><a href='?tbl=" . $record->id_table . "'>" . $tn . "</li>";
		}
	$html.='</ul>';
return $html;
}

function enpimodule_menu() {
    $items = array();

    $items['enpimodule/hello'] = array(
        'title' => 'Hello World Test',
        'page callback' => 'say_hello_world',
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
     );

		 $items['enpimodule/hello/insert'] = array(
        'title' => 'Hello World Insert',
        'page callback' => 'say_hello_world_insert',
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
     );

    return $items;
}

function say_hello_world() {
	drupal_add_css( "sites/all/modules/enpimodule/enpimodule.css" );

		$table = 'test';
		
		$html  = t('Document page');
		if( isset($_REQUEST['tbl']) )
		{
			//get the form!!!
			$id_table = $_REQUEST['tbl'];
			$aForm    = dbmng_get_form_array($id_table);

			//the param array stores some custom variable used by the renderer
			//hidden_vars are some hidden variables used by the form creation
			$aParam                         = array();
			$aParam['hidden_vars']          = array();
			$aParam['hidden_vars']['tbl']	  = $_REQUEST['tbl'];		

			//test filter records with a specific uid
			global $user;
			$aParam['filters']              = array();
			$aParam['filters']['id_user']	  = $user->uid;		

			$aParam['tbl_footer']           = 1;
/*
			$aParam['user_function']['dup']	=  0;		
			$aParam['user_function']['ins']	=  0;		
			$aParam['user_function']['upd']	=  1;		
			$aParam['user_function']['del']	=  1;		
*/
			//print_r ($aParam['filters']);
	
			// update record
			dbmng_create_form_update($aForm, $aParam);
	
			// insert record
			dbmng_create_form_insert($aForm, $aParam);
			
			// delete record
			dbmng_create_form_delete($aForm, $aParam);
			
			// duplicate record
			dbmng_create_form_duplicate($aForm, $aParam);
	
			$html .= dbmng_create_table($aForm, $aParam);
	
			$html .= dbmng_create_form($aForm, $aParam);
		}
	    return ($html);

}


function say_hello_world_insert() {
		$html=t('This is a new page for insert');
    return ($html);
}
