<?php

include_once "sites/all/library/dbmng/dbmng.php";

//******************************************************************************
// Drupal Module 
// ====================
// Query
//******************************************************************************
function enpimodule_block_info() {
$blocks = array();
$blocks['last_item'] = array(
'info' => t('Last item'),
);

return $blocks;
}

function enpimodule_block_view($delta='') {
$block = array();

switch($delta) {
case 'last_item' :
$block['content'] = last_item_view();
break;
}

return $block;
}

function last_item_view() {
$html='';
$result = db_query('SELECT distinct id_test, nome FROM test order by nome desc ');
	$html.='<ul>';
		foreach ($result as $record) {
			$html.='<li><a href="?update_id_test=' . $record->id_test . '">' . $record->nome . '</li>';
		}
	$html.='</ul>';
return $html;
}

function enpimodule_menu() {
    $items = array();

    $items['enpimodule/hello'] = array(
        'title' => 'Hello World Test',
        'page callback' => 'say_hello_world',
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
     );

		 $items['enpimodule/hello/insert'] = array(
        'title' => 'Hello World Insert',
        'page callback' => 'say_hello_world_insert',
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
     );

    return $items;
}

function say_hello_world() {

		$table = 'test';
		
		$html  = t('Document page');

		if(isset($_POST['nome'])){
			// aggiornamento record esistente
			if(isset($_POST['update_record'])){
				$result = db_query('update ' . $table . ' set nome=:nome, eta=:eta WHERE id_test=:id_test', 
					array( 
						':nome' => $_POST['nome'] ,
						':eta' => intval($_POST['eta']), 
						':id_test' => intval($_POST['update_record'])
					)
				);
			}
			else{ //inserimento nuovo record
				$result = db_query('insert into ' . $table . ' (nome, eta) values (:nome, :eta)', 
					array( 
						':nome' => $_POST['nome'] ,
						':eta' => intval($_POST['eta']) 
					)
				);
			}
		}
		
		// delete record
		if(isset($_REQUEST['delete_id_test'])){				
			$result = db_query('delete from ' . $table . ' WHERE id_test=:id_test', 
				array( 
					':id_test' => intval($_REQUEST['delete_id_test'])
				)
			);
		}

		// delete record
		if(isset($_REQUEST['duplicate_id_test'])){				
			$result = db_query('insert into ' . $table . ' (nome, eta) select nome, eta from ' . $table . ' WHERE id_test=:id_test', 
				array( 
					':id_test' => intval($_REQUEST['duplicate_id_test'])
				)
			);
		}
		
		$sql = 'select * from ' . $table;
		$result = db_query($sql);
    
    $html .= getVersion().'<table><tr><th>' . t('id_test') . '</th><th>' . t('name') . '</th><th>' . t('age') . '</th><th>' . t('functions') . '</th></tr>';

		foreach ($result as $record) {
			$html .= '<tr><td>' . $record->id_test . '</td><td>' . $record->nome.'</td><td>' . $record->eta . '</td>';

			$html .= '<td>';
				$html .= '<a href="?delete_id_test=' . $record->id_test.'">' . t('Delete') . '</a>' . '&nbsp;';
				$html .= '<a href="?update_id_test=' . $record->id_test . '">' . t('Update') . '</a>' . '&nbsp;';
				$html .= '<a href="?duplicate_id_test=' . $record->id_test . '">' . t('Duplicate') . '</a>';
			$html .= '</td>';
			
			$html .= '</tr>';
		}
    $html .= '</table>';
		
		$html .= '<a href="?insert_new=1">' . t('Insert new data') . '</a><br />';

		$nome_val       = '';
		$eta_val        = '';
		$update_id_test = '';

		if(isset($_REQUEST['update_id_test'])){
			$result = db_query('select * from ' . $table . ' where id_test=:id_test', array(':id_test' => intval($_REQUEST['update_id_test'])) );
	    foreach ($result as $record) {
           $nome_val       = $record->nome;
           $eta_val        = $record->eta;
           $update_id_test = $record->id_test;
			}
		}
	
		// form per inserimento e modifica
    if( isset($_GET['insert_new']) || isset($_GET['update_id_test']) ){
	    $html .= '<form method="POST" action="?" >';
			$html .= t('Name') . ': <input name="nome" value="' . $nome_val . '" /><br />';
			$html .= t('Age') . ': <input name="eta" value="' . $eta_val . '" /><br />';
			if($update_id_test!=''){
				$html .= '<input type="hidden" name="update_record" value="'.$update_id_test.'" />';
				$html .= '<input type="submit" value="'. t('Update') .'" />';
			}
			else{
				$html .= '<input type="submit" value="' .t('Insert') .'" />';
			}
	    $html .= '</form>';
    }
		
		$html .= "<br /><br />\n";
		
		/*
		// array che deve essere generato dinamicamente
		$aFormS = array();
		$aFormS['nome'] = array('label' => 'Name', 'type' => 'text', 'default' => '', 'value' => "Michele");
		$aFormS['eta'] = array('label' => 'Age', 'type' => 'number', 'default' => '', 'value' => null);

		$aForm= array(				
				'table_name' => 'test',
				'primary_key' => 'id_test',
				'fields' => array(
					array(
							'field_name' => 'name',
							'field_label' => 'Nome',
							'field_type' => 'text',
						),
					array(
							'field_name' => 'eta',
							'field_label' => 'Et&agrave',								
							'field_type' => 'text'
						),
				)
			);
		*/
		
		$aForm = array();
		$fields = db_query("select * from dbmng_fields where id_table=1 order by field_order ASC");
		foreach ($fields as $fld)
		{
			$sType = "";
			switch( $fld->id_field_type )
			{
				case "varchar":
					$sType = "text";
					break;

				case "int":
					$sType = "text";
					break;
				
				default:
					$sType = "text";
			}
			
			$aForm[$fld->field_name] = array('label' => $fld->field_label, 'type' => $sType, 'default' => $fld->default_value, 'value' => null);
		}

		// ----> inizio funzione
    $html .= "<form method='POST' action='?' >\n";
		foreach ( $aForm as $x => $x_value )
		{
			$html .= t($x_value['label']);
			$html .= "<input name='".$x."' ";
			$html .= "type='".$x_value['type']."' ";
			if( $x_value['value'] == null )
				$html .= "value='" . $x_value['default'] . "' ";
			else
				$html .= "value='" . $x_value['value'] . "' ";
			$html .= "><br />\n";
						
		}
		$html .= "<input type='submit' value='" .t('Insert') . "' />\n";
    $html .= "</form>\n";
		// fine funzione

    return ($html);

}


function say_hello_world_insert() {
		$html=t('This is a new page for insert');
    return ($html);
}
