<?php
include_once "sites/all/libraries/dbmng/dbmng.php";


function climasouth_video_block_info() 
{
	$blocks = array();
	$blocks['cs_video'] = array(
		'info' => t('Climasouth video contest block'),
		);
	return $blocks;
}


function climasouth_video_block_view($delta='') 
{
	$block = array();
	
	switch($delta) 
		{
			case 'cs_video' :
				$block['content'] = cl_video_block();
				break;
		}
	
	return $block;
}


function climasouth_video_menu() 
{
  $items = array();

  $items['climasouth_video/video'] = array(
      'title' => 'Video Contest',
      'page callback' => 'cs_video_contest_page',
      'access arguments' => array('video content'),
      'type' => MENU_CALLBACK,
   );

  return $items;
}


function climasouth_video_permission() {
	return array(
			  		'video content' => array('title'=>t('View the video contest'))
					);
}


function cl_video_block()
{
	$html = "";
	
	return $html;
}


function cs_video_contest_page()
{

  //drupal_add_http_header('Content-Type', 'application/json');

	$html='<!DOCTYPE html>
			<html lang="en">

			<head>

				<meta charset="utf-8">
				<meta http-equiv="X-UA-Compatible" content="IE=edge">
				<meta name="viewport" content="width=device-width, initial-scale=1">
				<meta name="description" content="">
				<meta name="author" content="">

				<title>Scrolling Nav - Start Bootstrap Template</title>

				<!-- Bootstrap Core CSS -->
				<link href="../sites/all/modules/climasouth_video/css/bootstrap.min.css" rel="stylesheet">

				<!-- Custom CSS -->
				<link href="../sites/all/modules/climasouth_video/css/scrolling-nav.css" rel="stylesheet">

				<!--[if lt IE 9]>
					<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
					<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
				<![endif]-->

			</head>

			<!-- The #page-top ID is part of the scrolling feature - the data-spy and data-target are part of the built-in Bootstrap scrollspy function -->

			<body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">

				<!-- Navigation -->
				<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
					<div class="container">
							<div class="navbar-header page-scroll">
								<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
									<span class="sr-only">Toggle navigation</span>
									<span class="icon-bar"></span>
									<span class="icon-bar"></span>
									<span class="icon-bar"></span>
								</button>
								<a class="navbar-brand page-scroll" href="#page-top">Start Bootstrap</a>
							</div>

							<!-- Collect the nav links, forms, and other content for toggling -->
							<div class="collapse navbar-collapse navbar-ex1-collapse">
								<ul class="nav navbar-nav">
									<!-- Hidden li included to remove active class from about link when scrolled up past about section -->
									<li class="hidden">
											<a class="page-scroll" href="#page-top"></a>
									</li>
									<li>
											<a class="page-scroll" href="#about">About</a>
									</li>
									<li>
											<a class="page-scroll" href="#services">Services</a>
									</li>
									<li>
											<a class="page-scroll" href="#contact">Contact</a>
									</li>
								</ul>
							</div>
							<!-- /.navbar-collapse -->
					</div>
					<!-- /.container -->
				</nav>

				<!-- Intro Section -->
				<section id="intro" class="intro-section">
					<div class="container">
							<div class="row">
								<div class="col-lg-12">
									<h1>Scrolling Nav</h1>
									<p><strong>Usage Instructions:</strong> Make sure to include the <code>scrolling-nav.js</code>, <code>jquery.easing.min.js</code>, and <code>scrolling-nav.css</code> files. To make a link smooth scroll to another section on the page, give the link the <code>.page-scroll</code> class and set the link target to a corresponding ID on the page.</p>
									<a class="btn btn-default page-scroll" href="#about">Click Me to Scroll Down!</a>
								</div>
							</div>
					</div>
				</section>

				<!-- About Section -->
				<section id="about" class="about-section">
					<div class="container">
							<div class="row">
								<div class="col-lg-12">
									<h1>About Section</h1>
								</div>
							</div>
					</div>
				</section>

				<!-- Services Section -->
				<section id="services" class="services-section">
					<div class="container">
							<div class="row">
								<div class="col-lg-12">
									<h1>Services Section</h1>
								</div>
							</div>
					</div>
				</section>

				<!-- Contact Section -->
				<section id="contact" class="contact-section">
					<div class="container">
							<div class="row">
								<div class="col-lg-12">
									<h1>Contact Section</h1>
								</div>
							</div>
					</div>
				</section>

				<!-- jQuery Version 1.11.0 -->
				<script src="../sites/all/modules/climasouth_video/js/jquery-1.11.0.js"></script>

				<!-- Bootstrap Core JavaScript -->
				<script src="../sites/all/modules/climasouth_video/js/bootstrap.min.js"></script>

				<!-- Scrolling Nav JavaScript -->
				<script src="../sites/all/modules/climasouth_video/js/jquery.easing.min.js"></script>
				<script src="../sites/all/modules/climasouth_video/js/scrolling-nav.js"></script>

			</body>

			</html>';


	echo $html;
}
